### ISSUE TITLE
Can't start instance

### ISSUE THREAD

**Issue by cemkoker** [misi/mm#11]
Continously complaining about redis; conn-refused

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at RedisClient.on_error (/opt/multiparty-meeting/server/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/opt/multiparty-meeting/server/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Container starting up...
- process.env.DEBUG: undefined
- config.mediasoup.logLevel: undefined
- config.mediasoup.logTags: undefined
events.js:174
      throw er; // Unhandled 'error' event
      ^

**Comment by misi** [comment]
@cemkoker Is a redis container, or local redis instance running and listening on localhost?

**Comment by cemkoker** [comment]
no, obviously not; but i do see a 'redis.conf' in your configs; but it doesn't get installed ? (Running CentOS 7)

**Comment by misi** [comment]
try to use` docker-compose up -d`

**Comment by cemkoker** [comment]
# docker-compose up

```
Building mm
Step 1/31 : FROM node:lts-alpine AS mm-builder
ERROR: Service 'mm' failed to build: Error parsing reference: "node:lts-alpine AS mm-builder" is not a valid repository/tag: invalid reference format
```

**Comment by misi** [comment]
Sorry I missed to tell use `docker-compos pull` first.

**Comment by cemkoker** [comment]
Thanks ! It worked ! Now i just need to solve the websocket issue 

websocket.js:120 WebSocket connection to 'wss://xxx.com/socket.io/?peerId=awskomok&roomId=test&EIO=3&transport=websocket&sid=fTEiAsQKoNuUwcsyAAAF' failed: Connection closed before receiving a handshake response

**Comment by misi** [comment]
It seems firewall or something network related issue

**Comment by misi** [comment]
@cemkoker Let me know if I can help you more..

**Comment by misi** [comment]
I will close this please open a new issue if I can help you more.

**Comment by cemkoker** [comment]
thanks; to confirm mm needs to have ports 443 and 40000-49999 UDP open correct ?

**Comment by misi** [comment]
You didn't wrote it, because maybe it is trivial that 443 is also tcp..
Ans Yes these ports are needed, and maybe tcp/80 is also good to have, but not mandatory.

**Comment by cemkoker** [comment]
Yes because the network where i'm setting up this is very complex and has DirectAccess (so IPv6 > IPv4 translation); so WebRTC doesn't support that. Problem solved.
