### ISSUE TITLE
Container status "Restarting", can't even enter container command line

### ISSUE THREAD

**Issue by createwebinar** [misi/mm#7]
I have doker-ce and docker-compose installed:
```
apt-get install docker-ce
apt-get install docker-compose 
```

I have set up 2 and 3:
```
copy your cert in certs/cert.pem and certs/privkey.pem
configure your app side configs e.g. Set TURN server and credential in configs/app/config.js
```
I didn't find any settings in configs/server/config.js to setup 4. So did nothing.

Next, after ./run.sh I get:
0ab1ceb0d9b0        misi/mm:latest      "/docker-entrypoint.…"   16 seconds ago      **Restarting (1) Less** than a second ago                       mm

**Comment by createwebinar** [comment]
Made it work with
`docker-compose up --detach`
instead of run.sh
Don't forget to update your docker compose to support version: "3.3".

**Comment by JagdishTech** [comment]
It is keep restarting, how to open web app ?
![image](https://user-images.githubusercontent.com/89624981/145938395-f25b3b4b-546a-4e70-8918-180f1b2c9246.png)
