### ISSUE TITLE
room names

### ISSUE THREAD

**Issue by csabibela** [misi/mm#8]
The MM opening from forces uppercase room names, but the users can write any character to the browser's URL field. The two rooms are different unfortunately.

```
room.dump():
{
  "roomId": "MzVkNTJm",
  "peers": 39
}
room.dump():
{
  "roomId": "mzvkntjm",
  "peers": 1
}
```

It would be good to combine these.

**Comment by misi** [comment]
I moved the issue here:   
havfo/multiparty-meeting#216
I close it here. Please follow it there..

Many thanks for the report!
I will fix it today..
