### ISSUE TITLE
UnhandledPromiseRejectionWarning digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

### ISSUE THREAD

**Issue by helfio** [misi/mm#9]
Hi,

I'm not very experienced in docker nor NodeJS but I'm trying to run this. I think I followed the README steps, but I've must missed something because when I try to run it, I get this error message:

> mm_1         | - process.env.DEBUG: undefined
mm_1         | - config.mediasoup.logLevel: undefined
mm_1         | - config.mediasoup.logTags: undefined
mm_1         | (node:6) UnhandledPromiseRejectionWarning: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
mm_1         |     at Object.createSecureContext (_tls_common.js:149:17)
mm_1         |     at Server.setSecureContext (_tls_wrap.js:1294:27)
mm_1         |     at Server (_tls_wrap.js:1158:8)
mm_1         |     at Server (https.js:68:14)
mm_1         |     at Server._init (/opt/multiparty-meeting/server/node_modules/spdy/lib/spdy/server.js:62:10)
mm_1         |     at new Server (/opt/multiparty-meeting/server/node_modules/spdy/lib/spdy/server.js:25:10)
mm_1         |     at Function.create (/opt/multiparty-meeting/server/node_modules/spdy/lib/spdy/server.js:30:12)
mm_1         |     at Object.create [as createServer] (/opt/multiparty-meeting/server/node_modules/spdy/lib/spdy/server.js:286:27)
mm_1         |     at runHttpsServer (/opt/multiparty-meeting/server/server.js:436:23)
mm_1         |     at run (/opt/multiparty-meeting/server/server.js:141:8)
mm_1         | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
mm_1         | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Redis and ouroboros images and containers seem to be working just fine, although Redis throws a couple of warnings regarding overcomit_memory and THP, which I'd say are not related to this issue and still didn't look into them.

I generated my own TLS certificate following this step (4th option): https://wiki.archlinux.org/index.php/OpenSSL#Usage

My system is an updated Archlinux which runs 
> Nombre                    : docker
Versión                   : 1:19.03.8-2
Nombre                    : docker-compose
Versión                   : 1.25.5-1

Any help would be appreciated.
Thanks!

**Comment by misi** [comment]
Double check  please that your new privkey is not encrypted..

**Comment by helfio** [comment]
Thank you so much! 
To be honest, I'm not familiar with this stuff and probably it wouldn't have come to my mind in any time, but it's clear now.

Do you think it's worth mentioning it in the README or something like that?

Cheers

**Comment by misi** [comment]
We can of course.. Thanks for the feedback.

**Comment by misi** [comment]
fixed it in commit ff423a21d05cf4ade58818bfe4b88572c4f44c43
